#The only difference between docker-compose.yaml and this debug file is moving
#from Dockerfile "ENTRYPOINT"  into "command" of the compose file
#don't forget in compose run config set=true "--build/force build images"

#create a network and add our services into this network:
#so, "app" service will be able to connect to the mysql database from "db" service by the hostname="db":
#jdbc:mysql://db:3306/DOCKERDB

#Connection url for connection in the DatabaseView:
#  jdbc:mysql://0.0.0.0:13306/DOCKERDB, login=root, password=root
#App is available at: http://localhost:8080/entitybus/post
version: "3.1"

networks:
  test:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test
    command: java -Djava.security.egd=file:/dev/./urandom -jar /project/target/demo-0.0.1-SNAPSHOT.jar

  db:
    image: 1000kit/h2
    container_name: db
    ports:
      - "8181:8181"
      - "1521:1521"
    volumes:
      - h2-data:/opt/h2-data
  volumes:
    -h2-data:
    
    healthcheck:
          test: ["CMD", "h2", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "DOCKERDB"]
          interval: 1s
          timeout: 3s
          retries: 30
    networks:
      - test
