name: 'Terraform GitHub Actions'
on:
  - push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::906861352598:role/gh
          region: us-east-1

      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        run: cd terraform && terraform init
      - name: 'Terraform Plan'
        run: terraform plan
      - name: 'Terraform Apply'
        run: terraform apply -auto-approve